# permissions for end users to edit bookings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: booking-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resource-booking-operator
    app.kubernetes.io/part-of: resource-booking-operator
    app.kubernetes.io/managed-by: kustomize
  name: booking-editor-role
rules:
  - apiGroups:
      - manager.kotaico.de
    resources:
      - bookings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - manager.kotaico.de
    resources:
      - bookings/status
    verbs:
      - get
