# permissions for end users to view bookingschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bookingscheduler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resource-booking-operator
    app.kubernetes.io/part-of: resource-booking-operator
    app.kubernetes.io/managed-by: kustomize
  name: bookingscheduler-viewer-role
rules:
- apiGroups:
  - manager.kotaico.de
  resources:
  - bookingschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manager.kotaico.de
  resources:
  - bookingschedulers/status
  verbs:
  - get
