# permissions for end users to view resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resource-booking-operator
    app.kubernetes.io/part-of: resource-booking-operator
    app.kubernetes.io/managed-by: kustomize
  name: resource-viewer-role
rules:
  - apiGroups:
      - manager.kotaico.de
    resources:
      - resources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - manager.kotaico.de
    resources:
      - resources/status
    verbs:
      - get
