

name: Publish

on:
  push:
    branches: [ main, publish-action ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::163217415796:role/ghaction-role-resource-booking-operator-Role-1D6W19HMVO1FV
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: resource-booking-operator
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make docker-build docker-push IMG=$REGISTRY/$REPOSITORY:$IMAGE_TAG
